import os

TESTING = False
DEBUG = False
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_SECRET_KEY = os.environ.get('SECRET_KEY')
JWT_ERROR_MESSAGE_KEY = 'error'
JWT_ACCESS_TOKEN_EXPIRES = 7200  # 2days
